### PR TITLE
Adaptive editor height & minor styling improvements

### PR DESCRIPTION
**Pull request by twiro**
- Editor height now adapts to the row-settings of the textarea
- Use Symphony's default font settings (instead of monospace fonts)
- Minor Styling improvements

### CODE REVIEW

**Comment by twiro** [comment]
oh and it would be great if you could tag the release as `0.3` after merging the PR - thanks!

**Comment by twiro** [comment]
Oups.

**Comment by twiro** [comment]
Dankeschön :)

**Comment by animaux** [comment]
Nein nein, ich habe zu danken!

**Pull request merged**
